apiVersion: v1
kind: Service
metadata:
  name: superset
  labels:
    app: superset
spec:
  selector:
    app: superset
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
  type: NodePort
