---
apiVersion: v1
kind: ConfigMap
metadata:
  name: superset-config
data:
  superset_config.py: |
    SECRET_KEY = '2SAJYqCC1PDsA/I7pyHJwt9V9ehr/jyO92YQPfIg2VI3EZjbotYwphtu'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
  labels:
    app: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
        - name: superset
          image: apache/superset:latest
          ports:
            - containerPort: 8088
          env:
            - name: SUPERSET_ENV
              value: production
            - name: DATABASE_URL
              value: postgresql://postgres:Y0c5emRHZHlaWE09@postgresql:5432/superset
            - name: TALISMAN_ENABLED
              value: "false"  # Tắt tính năng TALISMAN
          volumeMounts:
            - name: superset-data
              mountPath: /var/lib/superset
            - name: superset-config
              mountPath: /app/pythonpath/superset_config.py
              subPath: superset_config.py  # Mount tệp superset_config.py vào trong container
      initContainers:
        - name: init-superset
          image: apache/superset:latest
          command:
            - /bin/bash
            - -c
            - |
              superset db upgrade && \
              superset init && \
              superset fab create-admin --username admin --password admin --firstname Admin --lastname User --email admin@superset.com
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:Y0c5emRHZHlaWE09@postgresql:5432/superset
            - name: TALISMAN_ENABLED
              value: "false"  # Tắt tính năng TALISMAN
      volumes:
        - name: superset-data
          persistentVolumeClaim:
            claimName: superset-pvc
        - name: superset-config
          configMap:
            name: superset-config
---
apiVersion: v1
kind: Service
metadata:
  name: superset
spec:
  type: NodePort
  selector:
    app: superset
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
      nodePort: 30000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: superset-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
