apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
  labels:
    app: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
        - name: superset
          image: apache/superset:3.0.0
          ports:
            - containerPort: 8088
          env:
            - name: SUPERSET_AUTH_TYPE
              value: "AUTH_DB"
            - name: SUPERSET_AUTH_ROLE_PUBLIC
              value: "Admin"
            - name: FLASK_APP
              value: "superset"
            - name: SUPERSET_WEBSERVER_ADDRESS
              value: "0.0.0.0"
          volumeMounts:
            - name: superset-config
              mountPath: /app/superset_config.py
              subPath: superset_config.py
          command:
            - "/bin/sh"
            - "-c"
            - |
              superset db upgrade && \
              superset fab create-admin \
                --username admin \
                --firstname Superset \
                --lastname Admin \
                --email admin@example.com \
                --password admin || true && \
              superset init && \
              superset run -h 0.0.0.0 -p 8088
      volumes:
        - name: superset-config
          configMap:
            name: superset-config

---
apiVersion: v1
kind: Service
metadata:
  name: superset-service
  labels:
    app: superset
spec:
  selector:
    app: superset
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8088