apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
  labels:
    app: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      initContainers:
        - name: init-db
          image: khoaihps1/airflow:latest
          command: ["airflow", "db", "migrate"]
          env:
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: "postgresql+psycopg2://postgres:Y0c5emRHZHlaWE09@postgresql:5432/airflow"

      containers:
        - name: airflow
          image: khoaihps1/airflow:latest
          command: ["airflow"]
          args: ["webserver"]
          ports:
            - containerPort: 8080
          env:
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: "postgresql+psycopg2://postgres:Y0c5emRHZHlaWE09@postgresql:5432/airflow"
            - name: AIRFLOW__CORE__DAGS_FOLDER
              value: "/opt/airflow/dags/repo/dags"
            - name: PYTHONPATH
              value: /opt/airflow/dags/repo
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_PASSWORD

          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags

        - name: scheduler
          image: khoaihps1/airflow:latest
          command: [ "airflow" ]
          args: [ "scheduler" ]
          env:
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: "postgresql+psycopg2://postgres:Y0c5emRHZHlaWE09@postgresql:5432/airflow"
            - name: AIRFLOW__CORE__DAGS_FOLDER
              value: "/opt/airflow/dags/repo/dags"
            - name: PYTHONPATH
              value: /opt/airflow/dags/repo
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags

        - name: git-sync
          image: k8s.gcr.io/git-sync/git-sync:v3.6.2
          env:
            - name: GIT_SYNC_REPO
              value: "https://github.com/khoaihps/airflow.git"
            - name: GIT_SYNC_BRANCH
              value: "main"
            - name: GIT_SYNC_ROOT
              value: "/git"
            - name: GIT_SYNC_DEST
              value: "repo"
            - name: GIT_SYNC_WAIT
              value: "60"
            - name: GIT_SYNC_ONE_TIME
              value: "false"
          volumeMounts:
            - name: dags
              mountPath: /git

      volumes:
        - name: dags
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: airflow
  labels:
    app: airflow
spec:
  selector:
    app: airflow
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
