apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka:latest
          ports:
            - containerPort: 9093
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT"
            - name: KAFKA_LISTENER_NAME_PLAINTEXT
              value: "PLAINTEXT"
            - name: KAFKA_LISTENER_PORT_PLAINTEXT
              value: "9093"
            - name: KAFKA_ADVERTISED_LISTENER_NAME_PLAINTEXT
              value: "PLAINTEXT"
            - name: KAFKA_ADVERTISED_LISTENER_PORT_PLAINTEXT
              value: "9093"
